package com_paretointel_hl7v2_models


case class HD(Namespace_Id: String, Universal_Id: String, Universal_Id_Type: String)

case class MessageType(
                        messageType: String, triggerEvent: String, Structure: String
                      )

case class PersonLocation(
                           pointOfCare: String, room: String, bed: String, facility: String, locationStatus: String,
                           locationType: String, building: String, floor: String)


case class HL7Address(addressLine1: String,
                      addressLine2: String,
                      city: String,
                      state: String,
                      zip: String,
                      country: String
                     )

case class DateRange(StartDateTime: String, EndDateTime: String)

case class ExtendedCode(
                         identifier: String,
                         text: String,
                         codingSystem: String,
                         alternateIdentifier: String,
                         alternateText: String,
                         alternateCodingSystem: String
                       )

case class ExtendedPersonName(
                               LastName: String,
                               FirstName: String,
                               MiddleName: String,
                               Suffix: String,
                               Prefix: String,
                               Degree: String
                             )

case class ClinicianName(
                          identifier: String,
                          LastName: String,
                          FirstName: String,
                          MiddleName: String,
                          Suffix: String,
                          Prefix: String,
                          Degree: String
                        )

case class MSH(
                MSH_1_Field_Separator: String,
                MSH_2_Encoding_Characters: String,
                MSH_3_Sending_Application: String,
                MSH_4_Sending_Facility: String,
                MSH_5_Receiving_Application: String,
                MSH_6_Receiving_Facility: String,
                MSH_7_Date_Time_Of_Message: String,
                MSH_8_Security: String,
                MSH_9_Message_Type: MessageType,
                MSH_10_Message_Control_Id: String,
                MSH_11_Processing_Id: String,
                MSH_12_Version_Id: String,
                MSH_13_Sequence_Number: String,
                MSH_14_Continuation_Pointer: String,
                MSH_15_Accept_Acknowledgment_Type: String,
                MSH_16_Application_Acknowledgment_Type: String,
                MSH_17_Country_Code: String,
                MSH_18_Character_Set: String,
                MSH_19_Principal_Language_Of_Message: ExtendedCode,
                MSH_20_Alternate_Character_Set_Handling_Scheme: String,
                MSH_21_Message_Profile_Identifier: List[String],
                MSH_22_Sending_Responsible_Organization: String,
                MSH_23_Receiving_Responsible_Organization: String,
                MSH_24_Sending_Network_Address: String,
                MSH_25_Receiving_Network_Address: String
              )


case class EVN(
                EVN_1_Event_Type_Code: String,
                EVN_2_Recorded_Date_Time: String,
                EVN_3_Date_Time_Planned_Event: String,
                EVN_4_Event_Reason_Code: List[ExtendedCode],
                EVN_5_Operator_Id: ExtendedPersonName,
                EVN_6_Event_Occurred: String,
                EVN_7_Event_Facility: String
              )

case class PID(
                PID_1_Set_ID: String,
                PID_2_Patient_Id: String,
                PID_3_Patient_Identifier_List: List[String],
                PID_4_Alternate_Patient_Id_Pid: String,
                PID_5_Patient_Name: List[ExtendedPersonName],
                PID_6_Mothers_Maiden_Name: List[ExtendedPersonName],
                PID_7_Date_Time_Of_Birth: String,
                PID_8_Gender: ExtendedCode,
                PID_9_Patient_Alias: String,
                PID_10_Race: ExtendedCode,
                PID_11_Patient_Address: List[HL7Address],
                PID_12_County_Code: String,
                PID_13_Phone_Number_Home: List[String],
                PID_14_Phone_Number_Business: List[String],
                PID_15_Primary_Language: ExtendedCode,
                PID_16_Marital_Status: ExtendedCode,
                PID_17_Religion: ExtendedCode,
                PID_18_Patient_Account_Number: String,
                PID_18_5_Identifier_Type_Code: String,
                PID_19_Ssn_Number_Patient: String,
                PID_20_Drivers_License_Number_Patient: String,
                PID_21_Mothers_Identifier: List[ExtendedCode],
                PID_22_Ethnic_Group: ExtendedCode,
                PID_23_Birth_Place: String,
                PID_24_Multiple_Birth_Indicator: String,
                PID_25_Birth_Order: String,
                PID_26_Citizenship: List[ExtendedCode],
                PID_27_Veterans_Military_Status: ExtendedCode,
                PID_28_Nationality: ExtendedCode,
                PID_29_Patient_Death_Date_Time: String,
                PID_30_Patient_Death_Indicator: String,
                PID_31_Identity_Unknown_Indicator: String,
                PID_32_Identity_Reliability_Code: ExtendedCode,
                PID_33_Last_Update_Date_Time: String,
                PID_34_Last_Update_Facility: String,
                PID_38_Production_Class_Code: ExtendedCode,
                PID_39_Tribal_Citizenship: ExtendedCode,
                PID_40_Patient_Telecommunication_Information: String
              )

case class PID1(
                 PD1_1_Living_Dependency: ExtendedCode,
                 PD1_2_Living_Arrangement: ExtendedCode,
                 PD1_3_Patient_Primary_Facility: String,
                 PD1_4_Patient_Primary_Care_Provider_Name_Id_No: String,
                 PD1_5_Student_Indicator: ExtendedCode,
                 PD1_6_Handicap: ExtendedCode,
                 PD1_7_Living_Will_Code: ExtendedCode,
                 PD1_8_Organ_Donor_Code: ExtendedCode,
                 PD1_9_Separate_Bill: String,
                 PD1_10_Duplicate_Patient: List[ExtendedCode],
                 PD1_11_Publicity_Code: ExtendedCode,
                 PD1_12_Protection_Indicator: String,
                 PD1_13_Protection_Indicator_Effective_Date: String,
                 PD1_14_Place_Of_Worship: List[String],
                 PD1_15_Advance_Directive_Code: ExtendedCode,
                 PD1_16_Immunization_Registry_Status: ExtendedCode,
                 PD1_17_Immunization_Registry_Status_Effective_Date: String,
                 PD1_18_Publicity_Code_Effective_Date: String,
                 PD1_19_Military_Branch: ExtendedCode,
                 PD1_20_Military_Rank_Grade: ExtendedCode,
                 PD1_21_Military_Status: ExtendedCode,
                 PD1_22_Advance_Directive_Last_Verified_Date: String
               )

case class ARV(
                ARV_1_Set_ID: String,
                ARV_2_ActionCode: ExtendedCode,
                ARV_3_Restriction: ExtendedCode,
                ARV_4_Reason: List[ExtendedCode],
                ARV_5_Special_Instructions: List[String],
                ARV_6_Date_Range: DateRange
              )

case class NK1(
                NK1_1_Set_Id_Nk1: String,
                NK1_2_Name: List[ExtendedPersonName],
                NK1_3_Relationship: ExtendedCode,
                NK1_4_Address: List[HL7Address],
                NK1_5_Phone_Number: List[String],
                NK1_6_Business_Phone_Number: List[String],
                NK1_7_Contact_Role: ExtendedCode,
                NK1_8_Start_Date: String,
                NK1_9_End_Date: String,
                NK1_10_Next_Of_Kin_Associated_Parties_Job_Title: String,
                NK1_11_Next_Of_Kin_Associated_Parties_Job_Code_Class: String,
                NK1_12_Next_Of_Kin_Associated_Parties_Employee_Number: String,
                NK1_13_Organization_Name_Nk1: List[String],
                NK1_14_Marital_Status: ExtendedCode,
                NK1_15_Administrative_Sex: ExtendedCode,
                NK1_16_Date_Time_Of_Birth: String,
                NK1_17_Living_Dependency: List[ExtendedCode],
                NK1_18_Ambulatory_Status: List[ExtendedCode],
                NK1_19_Citizenship: List[ExtendedCode],
                NK1_20_Primary_Language: ExtendedCode,
                NK1_21_Living_Arrangement: ExtendedCode,
                NK1_22_Publicity_Code: ExtendedCode,
                NK1_23_Protection_Indicator: String,
                NK1_24_Student_Indicator: ExtendedCode,
                NK1_25_Religion: ExtendedCode,
                NK1_26_Mothers_Maiden_Name: List[ExtendedPersonName],
                NK1_27_Nationality: ExtendedCode,
                NK1_28_Ethnic_Group: List[ExtendedCode],
                NK1_30_Contact_Person_Name: List[ExtendedPersonName],
                NK1_31_Contact_Person_Telephone: List[String],
                NK1_32_Contact_Person_Address: List[HL7Address],
                NK1_33_Next_Of_Kin_Associated_Party_ID: List[ExtendedCode],
                NK1_34_Job_Status: ExtendedCode,
                NK1_35_Race: List[ExtendedCode],
                NK1_36_Handicap: ExtendedCode,
                NK1_37_Contact_Person_SSN: String,
                NK1_38_Next_Of_Kin_Birth_Place: String,
                NK1_39_Vip_Indicator: ExtendedCode,
                NK1_40_Next_Of_Kin_Tel: String,
                NK1_41_ContactPersonInfo: String
              )

case class PV1(

                PV1_1_Set_Id_Pv1: String,
                PV1_2_Patient_Class: String,
                PV1_2_3_CodingSystem: String,
                PV1_3_Assigned_Patient_Location: PersonLocation,
                PV1_4_Admission_Type: ExtendedCode,
                PV1_5_Preadmit_Number: String,
                PV1_6_Prior_Patient_Location: PersonLocation,
                PV1_7_Attending_Doctor: List[ExtendedPersonName],
                PV1_8_Referring_Doctor: List[ExtendedPersonName],
                PV1_9_Consulting_Doctor: List[ExtendedPersonName],
                PV1_10_Hospital_Service: ExtendedCode,
                PV1_11_Temporary_Location: PersonLocation,
                PV1_12_Preadmit_Test_Indicator: ExtendedCode,
                PV1_13_Readmission_Indicator: ExtendedCode,
                PV1_14_Admit_Source: ExtendedCode,
                PV1_15_Ambulatory_Status: List[ExtendedCode],
                PV1_16_Vip_Indicator: ExtendedCode,
                PV1_17_Admitting_Doctor: List[ExtendedPersonName],
                PV1_19_Visit_Number: String,
                PV1_20_Financial_Class: List[String],
                PV1_20_2_EffectiveDate: String,
                PV1_21_Charge_Price_Indicator: ExtendedCode,
                PV1_22_Courtesy_Code: ExtendedCode,
                PV1_23_Credit_Rating: ExtendedCode,
                PV1_24_Contract_Code: List[ExtendedCode],
                PV1_25_Contract_Effective_Date: List[String],
                PV1_26_Contract_Amount: List[String],
                PV1_27_Contract_Period: List[String],
                PV1_28_Interest_Code: ExtendedCode,
                PV1_29_Transfer_To_Bad_Debt_Code: ExtendedCode,
                PV1_30_Transfer_To_Bad_Debt_Date: String,
                PV1_31_Bad_Debt_Agency_Code: ExtendedCode,
                PV1_32_Bad_Debt_Transfer_Amount: String,
                PV1_33_Bad_Debt_Recovery_Amount: String,
                PV1_34_Delete_Account_Indicator: ExtendedCode,
                PV1_35_Delete_Account_Date: String,
                PV1_36_Discharge_Disposition: ExtendedCode,
                PV1_37_Discharged_To_Location: String,
                pV1_37_2_EffectiveDate: String,
                PV1_38_Diet_Type: ExtendedCode,
                PV1_39_Servicing_Facility: ExtendedCode,
                PV1_40_Bed_Status: ExtendedCode,
                PV1_41_Account_Status: ExtendedCode,
                PV1_42_Pending_Location: PersonLocation,
                PV1_43_Prior_Temporary_Location: PersonLocation,
                PV1_44_Admit_Date_Time: String,
                PV1_45_Discharge_Date_Time: String,
                PV1_46_Current_Patient_Balance: String,
                PV1_47_Total_Charges: String,
                PV1_48_Total_Adjustments: String,
                PV1_49_Total_Payments: String,
                PV1_50_Alternate_Visit_Id: ExtendedCode,
                PV1_51_Visit_Indicator: ExtendedCode,
                PV1_52_Other_Healthcare_Provider: String,
                PV1_53_Service_Episode_Description: String,
                PV1_54_Service_Episode_Identifier: ExtendedCode
              )

case class PV2(
                PV2_1_Prior_Pending_Location: PersonLocation,
                PV2_2_Accommodation_Code: ExtendedCode,
                PV2_3_Admit_Reason: ExtendedCode,
                PV2_4_Transfer_Reason: ExtendedCode,
                PV2_5_Patient_Valuables: String,
                PV2_6_Patient_Valuables_Location: List[String],
                PV2_7_Visit_User_Code: List[ExtendedCode],
                PV2_8_Expected_Admit_DateTime: String,
                PV2_9_Expected_Discharge_DateTime: String,
                PV2_10_Estimated_Length_Of_Inpatient_Stay: String,
                PV2_11_Actual_Length_Of_Inpatient_Stay: String,
                PV2_12_Visit_Description: String,
                PV2_13_Referral_Source_Code: List[ExtendedPersonName],
                PV2_14_Previous_Service_Date: String,
                PV2_15_Employment_Illness_Related_Indicator: String,
                PV2_16_Purge_Status_Code: ExtendedCode,
                PV2_17_Purge_Status_Date: String,
                PV2_18_Special_Program_Code: ExtendedCode,
                PV2_19_Retention_Indicator: String,
                PV2_20_Expected_Number_Of_Insurance_Plans: String,
                PV2_21_Visit_Publicity_Code: ExtendedCode,
                PV2_22_Visit_Protection_Indicator: String,
                PV2_23_Clinic_Organization_Name: List[String],
                PV2_24_Patient_Status_Code: ExtendedCode,
                PV2_25_Visit_Priority_Code: ExtendedCode,
                PV2_26_Previous_Treatment_Date: String,
                PV2_27_Expected_Discharge_Disposition: ExtendedCode,
                PV2_28_Signature_On_File_Date: String,
                PV2_29_First_Similar_Illness_Date: String,
                PV2_30_Patient_Charge_Adjustment_Code: ExtendedCode,
                PV2_31_Recurring_Service_Code: ExtendedCode,
                PV2_32_Billing_Media_Code: String,
                PV2_33_Expected_Surgery_Date_And_Time: String,
                PV2_34_Military_Partnership_Code: String,
                PV2_35_Military_Non_availability_Code: String,
                PV2_36_Newborn_Baby_Indicator: String,
                PV2_37_Baby_Detained_Indicator: String,
                PV2_38_Mode_Of_Arrival_Code: ExtendedCode,
                PV2_39_Recreational_Drug_Use_Code: List[ExtendedCode],
                PV2_40_Admission_Level_Of_Care_Code: ExtendedCode,
                PV2_41_Precaution_Code: ExtendedCode,
                PV2_42_Patient_Condition_Code: List[ExtendedCode],
                PV2_43_Living_Will_Code: ExtendedCode,
                PV2_44_Organ_Donor_Code: ExtendedCode,
                PV2_45_Advance_Directive_Code: List[ExtendedCode],
                PV2_46_Patient_Status_Effective_Date: String,
                PV2_47_Expected_Loa_Return_DateTime: String,
                PV2_48_Expected_Pre_admission_Testing_Date_Time: String,
                PV2_49_Notify_Clergy_Code: List[ExtendedCode],
                PV2_50_Advance_Directive_Last_Verified_Date: String
              )

case class DB1(

                DB1_1_SetId_Db1: String,
                DB1_2_Disabled_Person_Code: ExtendedCode,
                DB1_3_Disabled_Person_Identifier: List[ExtendedCode],
                DB1_4_Disability_Indicator: String,
                DB1_5_Disability_Start_Date: String,
                DB1_6_Disability_End_Date: String,
                DB1_7_Disability_Return_To_Work_Date: String,
                DB1_8_Disability_Unable_To_Work_Date: String
              )

case class OBX(
                OBX_1_Set_Id_Obx: String,
                OBX_2_Value_Type: String,
                OBX_3_Observation_Identifier: ExtendedCode,
                OBX_4_Observation_Sub_id: String,
                OBX_5_Observation_Value: List[String],
                OBX_6_Units: ExtendedCode,
                OBX_7_References_Range: String,
                OBX_8_Interpretation_Codes: List[String],
                OBX_8_3_CodingSystem: String,
                OBX_9_Probability: String,
                OBX_10_Nature_Of_Abnormal_Test: List[String],
                OBX_11_Observation_Result_Status: String,
                OBX_12_Effective_Date_Of_Reference_Range: String,
                OBX_13_User_Defined_Access_Checks: String,
                OBX_14_Date_Time_Observation: String,
                OBX_15_Producer_Id: ExtendedCode,
                OBX_16_Responsible_Observer: List[ExtendedPersonName],
                OBX_17_Observation_Method: List[ExtendedCode],
                OBX_18_Equipment_Instance_Identifier: List[String],
                OBX_19_DateTime_Analysis: String,
                OBX_20_Observation_Site: List[ExtendedCode],
                OBX_21_Observation_Instance_Identifier: String,
                OBX_22_Mood_Code: ExtendedCode,
                OBX_23_Performing_Organization_Name: String,
                OBX_24_Performing_Organization_Address: HL7Address,
                OBX_25_Performing_Organization_Medical_Director: ExtendedPersonName,
                OBX_26_Patient_Results_Release_Category: String
              )

case class AL1(
                AL1_1_Set_Id_Al1: String,
                AL1_2_Allergen_Type_Code: ExtendedCode,
                AL1_3_Allergen_Code_Mnemonic_Description: ExtendedCode,
                AL1_4_Allergy_Severity_Code: ExtendedCode,
                AL1_5_Allergy_Reaction_Code: List[String],
                AL1_6_Identification_Date: String
              )

case class DG1(
                DG1_1_SetId_Dg1: String,
                DG1_2_Diagnosis_Coding_Method: String,
                DG1_3_Diagnosis_Code_Dg1: ExtendedCode,
                DG1_4_Diagnosis_Description: String,
                DG1_5_Diagnosis_DateTime: String,
                DG1_6_Diagnosis_Type: ExtendedCode,
                DG1_7_Major_Diagnostic_Category: ExtendedCode,
                DG1_8_Diagnostic_Related_Group: ExtendedCode,
                DG1_9_Drg_Approval_Indicator: String,
                DG1_10_Drg_Grouper_Review_Code: ExtendedCode,
                DG1_11_Outlier_Type: ExtendedCode,
                DG1_12_Outlier_Days: String,
                DG1_13_Outlier_Cost: String,
                DG1_14_Grouper_Version_And_Type: String,
                DG1_15_Diagnosis_Priority: String,
                DG1_16_Diagnosing_Clinician: List[ExtendedPersonName],
                DG1_17_Diagnosis_Classification: ExtendedCode,
                DG1_18_Confidential_Indicator: String,
                DG1_19_Attestation_DateTime: String,
                DG1_20_Diagnosis_Identifier: ExtendedCode,
                DG1_21_Diagnosis_Action_Code: String,
                DG1_22_Parent_Diagnosis: ExtendedCode,
                DG1_23_Drg_Ccl_Value_Code: ExtendedCode,
                DG1_24_Drg_Grouping_Usage: String,
                DG1_25_Drg_Diagnosis_Determination_Status: ExtendedCode,
                DG1_26_POA_Indicator: ExtendedCode
              )

case class DRG(
                DRG_1_Diagnostic_Related_Group: ExtendedCode,
                DRG_2_Drg_Assigned_Date_Time: String,
                DRG_3_Drg_Approval_Indicator: String,
                DRG_4_Drg_Grouper_Review_Code: ExtendedCode,
                DRG_5_Outlier_Type: ExtendedCode,
                DRG_6_Outlier_Days: String,
                DRG_7_Outlier_Cost: String,
                DRG_8_Drg_Payor: ExtendedCode,
                DRG_9_Outlier_Reimbursement: String,
                DRG_10_Confidential_Indicator: String,
                DRG_11_Drg_Transfer_Type: ExtendedCode,
                DRG_12_Name_Of_Coder: ExtendedPersonName,
                DRG_13_Grouper_Status: ExtendedCode,
                DRG_14_Pccl_Value_Code: ExtendedCode,
                DRG_15_Effective_Weight: String,
                DRG_16_Monetary_Amount: String,
                DRG_17_Status_Patient: ExtendedCode,
                DRG_18_Grouper_Software_Name: String,
                DRG_19_Grouper_Software_Version: String,
                DRG_20_Status_Financial_Calculation: ExtendedCode,
                DRG_21_Relative_Discount_Surcharge: String,
                DRG_22_Basic_Charge: String,
                DRG_23_Total_Charge: String,
                DRG_24_Discount_Surcharge: String,
                DRG_25_Calculated_Days: String,
                DRG_26_Status_Gender: ExtendedCode,
                DRG_27_Status_Age: ExtendedCode,
                DRG_28_Status_Length_Of_Stay: ExtendedCode,
                DRG_29_Status_Same_Day_Flag: ExtendedCode,
                DRG_30_Status_Separation_Mode: ExtendedCode,
                DRG_31_Status_Weight_At_Birth: ExtendedCode,
                DRG_32_Status_Respiration_Minutes: ExtendedCode,
                DRG_33_Status_Admission: ExtendedCode

              )

case class PR1(
                PR1_1_SetId_Pr1: String,
                PR1_2_Procedure_Coding_Method: String,
                PR1_3_Procedure_Code: ExtendedCode,
                PR1_4_Procedure_Description: String,
                PR1_5_Procedure_DateTime: String,
                PR1_6_Procedure_Functional_Type: ExtendedCode,
                PR1_7_Procedure_Minutes: String,
                PR1_8_Anesthesiologist: String,
                PR1_9_Anesthesia_Code: ExtendedCode,
                PR1_10_Anesthesia_Minutes: String,
                PR1_11_Surgeon: String,
                PR1_12_Procedure_Practitioner: String,
                PR1_13_Consent_Code: ExtendedCode,
                PR1_14_Procedure_Priority: String,
                PR1_15_Associated_Diagnosis_Code: ExtendedCode,
                PR1_16_Procedure_Code_Modifier: List[ExtendedCode],
                PR1_17_Procedure_Drg_Type: ExtendedCode,
                PR1_18_Tissue_TypeCode: List[ExtendedCode],
                PR1_19_Procedure_Identifier: ExtendedCode,
                PR1_20_Procedure_Action_Code: String,
                PR1_21_Drg_Procedure_Determination_Status: ExtendedCode,
                PR1_22_Drg_Procedure_Relevance: ExtendedCode,
                PR1_23_Treating_Organizational_Unit: List[PersonLocation],
                PR1_24_Respiratory_Within_Surgery: String,
                PR1_25_Parent_Procedure_Id: ExtendedCode
              )

case class GT1(
                GT1_1_SetId_Gt1: String,
                GT1_2_Guarantor_Number: List[ExtendedCode],
                GT1_3_Guarantor_Name: List[ExtendedPersonName],
                GT1_4_Guarantor_Spouse_Name: List[ExtendedPersonName],
                GT1_5_Guarantor_Address: List[HL7Address],
                GT1_6_Guarantor_PhNum_Home: List[String],
                GT1_7_Guarantor_PhNum_Business: List[String],
                GT1_8_Guarantor_DateTime_Of_Birth: String,
                GT1_9_Guarantor_Administrative_Sex: ExtendedCode,
                GT1_10_Guarantor_Type: ExtendedCode,
                GT1_11_Guarantor_Relationship: ExtendedCode,
                GT1_12_Guarantor_Ssn: String,
                GT1_13_Guarantor_Date_Begin: String,
                GT1_14_Guarantor_Date_End: String,
                GT1_15_Guarantor_Priority: String,
                GT1_16_Guarantor_Employer_Name: List[ExtendedPersonName],
                GT1_17_Guarantor_Employer_Address: List[HL7Address],
                GT1_18_Guarantor_Employer_Phone_Number: List[String],
                GT1_19_Guarantor_Employee_Id_Number: List[ExtendedCode],
                GT1_20_Guarantor_Employment_Status: ExtendedCode,
                GT1_21_Guarantor_Organization_Name: List[String],
                GT1_22_Guarantor_Billing_Hold_Flag: String,
                GT1_23_Guarantor_Credit_Rating_Code: ExtendedCode,
                GT1_24_Guarantor_Death_Date_And_Time: String,
                GT1_25_Guarantor_Death_Flag: String,
                GT1_26_Guarantor_Charge_Adjustment_Code: ExtendedCode,
                GT1_27_Guarantor_Household_Annual_Income: String,
                GT1_28_Guarantor_Household_Size: String,
                GT1_29_Guarantor_Employer_Id_Number: ExtendedCode,
                GT1_30_Guarantor_Marital_Status_Code: ExtendedCode,
                GT1_31_Guarantor_Hire_Effective_Date: String,
                GT1_32_Employment_Stop_Date: String,
                GT1_33_Living_Dependency: ExtendedCode,
                GT1_34_Ambulatory_Status: List[ExtendedCode],
                GT1_35_Citizenship: List[ExtendedCode],
                GT1_36_Primary_Language: String,
                GT1_37_Living_Arrangement: String,
                GT1_38_Publicity_Code: ExtendedCode,
                GT1_39_Protection_Indicator: String,
                GT1_40_Student_Indicator: ExtendedCode,
                GT1_41_Religion: ExtendedCode,
                GT1_42_Mothers_Maiden_Name: List[ExtendedPersonName],
                GT1_43_Nationality: ExtendedCode,
                GT1_44_Ethnic_Group: List[ExtendedCode],
                GT1_45_Contact_Persons_Name: List[ExtendedPersonName],
                GT1_46_Contact_Persons_Telephone_Number: List[String],
                GT1_47_Contact_Reason: ExtendedCode,
                GT1_48_Contact_Relationship: ExtendedCode,
                GT1_49_Job_Title: String,
                GT1_50_Job_CodeClass: String,
                GT1_51_Guarantor_Employers_Organization_Name: List[String],
                GT1_52_Handicap: String,
                GT1_53_Job_Status: String,
                GT1_54_Guarantor_Financial_Class: String,
                GT1_55_Guarantor_Race: List[ExtendedCode],
                GT1_56_Guarantor_Birth_Place: String,
                GT1_57_Vip_Indicator: ExtendedCode
              )

case class IN1(
                IN1_1_SetId_In1: String,
                IN1_2_Health_Plan_Id: ExtendedCode,
                IN1_3_Insurance_Company_Id: List[ExtendedCode],
                IN1_4_Insurance_Company_Name: List[String],
                IN1_5_Insurance_Company_Address: List[HL7Address],
                IN1_6_Insurance_Co_Contact_Person: List[ExtendedPersonName],
                IN1_7_Insurance_Co_Phone_Number: List[String],
                IN1_8_Group_Number: String,
                IN1_9_Group_Name: List[String],
                IN1_10_Insureds_Group_Emp_Id: List[String],
                IN1_11_Insureds_Group_Emp_Name: List[String],
                IN1_12_Plan_Effective_Date: String,
                IN1_13_Plan_Expiration_Date: String,
                IN1_14_Authorization_Information: String,
                IN1_15_Plan_Type: ExtendedCode,
                IN1_16_Name_Of_Insured: List[ExtendedPersonName],
                IN1_17_Insureds_Relationship_To_Patient: ExtendedCode,
                IN1_18_Insureds_Date_Of_Birth: String,
                IN1_19_Insureds_Address: List[HL7Address],
                IN1_20_Assignment_Of_Benefits: ExtendedCode,
                IN1_21_Coordination_Of_Benefits: ExtendedCode,
                IN1_22_Coord_Of_Ben__Priority: String,
                IN1_23_Notice_Of_Admission_Flag: String,
                IN1_24_Notice_Of_Admission_Date: String,
                IN1_25_Report_Of_Eligibility_Flag: String,
                IN1_26_Report_Of_Eligibility_Date: String,
                IN1_27_Release_Information_Code: ExtendedCode,
                IN1_28_Pre_admit_Cert: String,
                IN1_29_Verification_DateTime: String,
                IN1_30_Verification_By: List[String],
                IN1_31_Type_Of_Agreement_Code: ExtendedCode,
                IN1_32_Billing_Status: ExtendedCode,
                IN1_33_Lifetime_Reserve_Days: String,
                IN1_34_Delay_Before_L_r__Day: String,
                IN1_35_Company_Plan_Code: ExtendedCode,
                IN1_36_Policy_Number: String,
                IN1_37_Policy_Deductible: String,
                IN1_38_Policy_Limit_Amount: String,
                IN1_39_Policy_Limit_Days: String,
                IN1_40_Room_Rate_Semi_private: String,
                IN1_41_Room_Rate_Private: String,
                IN1_42_Insureds_Employment_Status: ExtendedCode,
                IN1_43_Insureds_Administrative_Sex: ExtendedCode,
                IN1_44_Insureds_Employers_Address: List[HL7Address],
                IN1_45_Verification_Status: String,
                IN1_46_Prior_Insurance_Plan_Id: String,
                IN1_47_Coverage_Type: String,
                IN1_48_Handicap: String,
                IN1_49_Insureds_Id_Number: List[ExtendedCode],
                IN1_50_Signature_Code: String,
                IN1_51_Signature_Code_Date: String,
                IN1_52_Insureds_Birth_Place: String,
                IN1_53_Vip_Indicator: ExtendedCode,
                IN1_54_External_Health_Plan_Identifiers: List[ExtendedCode]
              )

case class IN2(
                IN2_1_InsuredsEmployeeId: List[ExtendedCode],
                IN2_2_Insureds_SSN: String,
                IN2_3_Insureds_Employers_Name: List[ExtendedPersonName],
                IN2_4_Employer_Information_Data: ExtendedCode,
                IN2_5_Mail_Claim_Party: ExtendedCode,
                IN2_6_Medicare_Health_Ins_Card_Number: String,
                IN2_7_Medicaid_Case_Name: List[ExtendedPersonName],
                IN2_8_Medicaid_Case_Number: String,
                IN2_9_Military_Sponsor_Name: List[ExtendedPersonName],
                IN2_10_Military_Id_Number: String,
                IN2_11_Dependent_Of_Military_Recipient: String,
                IN2_12_Military_Organization: ExtendedCode,
                IN2_13_Military_Station: String,
                IN2_14_Military_Service: ExtendedCode,
                IN2_15_Military_Rank_Grade: ExtendedCode,
                IN2_16_Military_Status: ExtendedCode,
                IN2_17_Military_Retire_Date: String,
                IN2_18_Military_Non_avail_Cert_On_File: String,
                IN2_19_Baby_Coverage: String,
                IN2_20_Combine_Baby_Bill: String,
                IN2_21_Blood_Deductible: String,
                IN2_22_Special_Coverage_Approval_Name: List[ExtendedPersonName],
                IN2_23_Special_Coverage_Approval_Title: String,
                IN2_24_Non_covered_Insurance_Code: List[String],
                IN2_25_Payor_Id: List[ExtendedCode],
                IN2_26_Payor_Subscriber_Id: List[ExtendedCode],
                IN2_27_Eligibility_Source: String,
                IN2_28_Room_Coverage_Type_Amount: List[String],
                IN2_29_Policy_Type_Amount: List[String],
                IN2_30_Daily_Deductible: String,
                IN2_31_Living_Dependency: ExtendedCode,
                IN2_32_Ambulatory_Status: List[ExtendedCode],
                IN2_33_Citizenship: List[ExtendedCode],
                IN2_34_Primary_Language: ExtendedCode,
                IN2_35_Living_Arrangement: ExtendedCode,
                IN2_36_Publicity_Code: ExtendedCode,
                IN2_37_Protection_Indicator: String,
                IN2_38_Student_Indicator: ExtendedCode,
                IN2_39_Religion: ExtendedCode,
                IN2_40_Mothers_Maiden_Name: List[ExtendedPersonName],
                IN2_41_Nationality: ExtendedCode,
                IN2_42_Ethnic_Group: List[ExtendedCode],
                IN2_43_Marital_Status: List[ExtendedCode],
                IN2_44_Insureds_Employment_Start_Date: String,
                IN2_45_Employment_Stop_Date: String,
                IN2_46_Job_Title: String,
                IN2_47_Job_Code_Class: String,
                IN2_48_Job_Status: ExtendedCode,
                IN2_49_Employer_Contact_Person_Name: List[ExtendedPersonName],
                IN2_50_Employer_Contact_Person_Phone_Number: List[String],
                IN2_51_Employer_Contact_Reason: String,
                IN2_52_Insureds_Contact_Persons_Name: List[ExtendedPersonName],
                IN2_53_Insureds_Contact_Person_Phone_Number: List[String],
                IN2_54_Insureds_Contact_Person_Reason: List[ExtendedCode],
                IN2_55_Relationship_To_The_Patient_Start_Date: String,
                IN2_56_Relationship_To_The_Patient_Stop_Date: List[String],
                IN2_57_Insurance_Co_Contact_Reason: ExtendedCode,
                IN2_58_Insurance_Co_Contact_Phone_Number: List[String],
                IN2_59_Policy_Scope: ExtendedCode,
                IN2_60_Policy_Source: ExtendedCode,
                IN2_61_Patient_Member_Number: ExtendedCode,
                IN2_62_Guarantors_Relationship_To_Insured: String,
                IN2_63_Insureds_Phone_Number_Home: List[String],
                IN2_64_Insureds_Employer_Phone_Number: List[String],
                IN2_65_Military_Handicapped_Program: ExtendedCode,
                IN2_66_Suspend_Flag: String,
                IN2_67_Copay_Limit_Flag: String,
                IN2_68_Stoploss_Limit_Flag: String,
                IN2_69_Insured_Organization_Name_And_Id: List[String],
                IN2_70_Insured_Employer_Organization_Name_And_Id: List[String],
                IN2_71_Race: ExtendedCode,
                IN2_72_Patients_Relationship_To_Insured: ExtendedCode
              )

case class IN3(
                IN3_1_Set_Id_In3: String,
                IN3_2_Certification_Number: String,
                IN3_3_Certified_By: List[ExtendedPersonName],
                IN3_4_Certification_Required: String,
                IN3_5_Penalty: String,
                IN3_6_Certification_DateTime: String,
                IN3_7_Certification_Modify_DateTime: String,
                IN3_8_Operator: List[ExtendedPersonName],
                IN3_9_Certification_Begin_Date: String,
                IN3_10_Certification_End_Date: String,
                IN3_11_Days: String,
                IN3_12_Non_concur_CodeDescription: ExtendedCode,
                IN3_13_Non_concur_Effective_DateTime: String,
                IN3_14_Physician_Reviewer: List[ExtendedPersonName],
                IN3_15_Certification_Contact: String,
                IN3_16_Certification_Contact_Phone_Number: List[String],
                IN3_17_Appeal_Reason: ExtendedCode,
                IN3_18_Certification_Agency: ExtendedCode,
                IN3_19_Certification_Agency_Phone_Number: List[String],
                IN3_20_Pre_certification_Requirement: List[String],
                IN3_21_Case_Manager: String,
                IN3_22_Second_Opinion_Date: String,
                IN3_23_Second_Opinion_Status: ExtendedCode,
                IN3_24_Second_Opinion_Documentation_Received: List[ExtendedCode],
                IN3_25_Second_Opinion_Physician: List[ExtendedPersonName]
              )

case class ACC(
                ACC_1_Accident_Date_Time: String,
                ACC_2_Accident_Code: ExtendedCode,
                ACC_3_Accident_Location: String,
                ACC_4_Auto_Accident_State: ExtendedCode,
                ACC_5_Accident_Job_Related_Indicator: String,
                ACC_6_Accident_Death_Indicator: String,
                ACC_7_Entered_By: ExtendedPersonName,
                ACC_8_Accident_Description: String,
                ACC_9_Brought_In_By: String,
                ACC_10_Police_Notified_Indicator: String,
                ACC_11_Accident_Address: HL7Address,
                ACC_12_Degree_Of_Patient_Liability: String
              )

case class UB1(
                UB1_1_Set_Id_Ub1: String,
                UB1_2_Blood_Deductible: String,
                UB1_3_Blood_Furnished_pints: String,
                UB1_4_Blood_Replaced_pints: String,
                UB1_5_Blood_Not_Replaced_pints: String,
                UB1_6_Co_insurance_Days: String,
                UB1_7_Condition_Code: List[String],
                UB1_8_Covered_Days: String,
                UB1_9_Non_Covered_Days: String,
                UB1_10_Value_Amount_Code: List[String],
                UB1_11_Number_Of_Grace_Days: String,
                UB1_12_Special_Program_Indicator: String,
                UB1_13_Psro_Ur_Approval_Indicator: String,
                UB1_14_Psro_Ur_Approved_Stay_fm: String,
                UB1_15_Psro_Ur_Approved_Stay_to: String,
                UB1_16_Occurrence: List[String],
                UB1_17_Occurrence_Span: String,
                UB1_18_Occur_Span_Start_Date: String,
                UB1_19_Occur_Span_End_Date: String,
                UB1_20_Ub_82_Locator_2: String,
                UB1_21_Ub_82_Locator_9: String,
                UB1_22_Ub_82_Locator_27: String,
                UB1_23_Ub_82_Locator_45: String
              )

case class UB2(
                UB2_1_Set_Id_Ub2: String,
                UB2_2_Co_insurance_Days_9: String,
                UB2_3_Condition_Code_24_30: String,
                UB2_4_Covered_Days_7: String,
                UB2_5_Non_covered_Days_8: String,
                UB2_6_Value_Amount_Code: String,
                UB2_7_Occurrence_Code_Date_32_35: String,
                UB2_8_Occurrence_Span_Code_Dates_36: String,
                UB2_9_UB92_Locator_2__state: String,
                UB2_10_UB92_Locator_11_state: String,
                UB2_11_UB92_Locator_31_national: String,
                UB2_12_Document_Control_Number: String,
                UB2_13_UB92_Locator_49_national: String,
                UB2_14_UB92_Locator_56_state: String,
                UB2_15_UB92_Locator_57_national: String,
                UB2_16_UB92_Locator_78_state: String,
                UB2_17_Special_Visit_Count: String
              )

case class PDA(
                PDA_1_Death_Cause_Code: List[ExtendedCode],
                PDA_2_Death_Location: PersonLocation,
                PDA_3_Death_Certified_Indicator: String,
                PDA_4_Death_Certificate_Signed_DateTime: String,
                PDA_5_Death_Certified_By: ExtendedPersonName,
                PDA_6_Autopsy_Indicator: String,
                PDA_7_Autopsy_Start_And_End_DateTime: String,
                PDA_8_Autopsy_Performed_By: String,
                PDA_9_Coroner_Indicator: String
              )


case class SegementKey(segment:String, expression:String, repeatable: Boolean)





